# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autuor',
            new_name='author',
        ),
    ]
